---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте.
  - Пользователь должен иметь возможность создавать игры и играть с ботом или приглашать других игроков к участию в батле.
  - Пользователь должен иметь возможность наблюдать за чужой игрой.
  - Пользователь должен иметь возможность участвовать в чате с соперником и зрителями.
  - Пользователь должен иметь возможность создавать новые задачи.
  - У пользователя должна быть возможность выбрать уровень сложности игры.
  - Пользователь должен иметь возможность видеть код соперника в реальном времени и результаты запуска тестов.
  - Пользователь должен иметь возможность выбрать язык решения задачи.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей).
implicit:
  - Пользователь может иметь возможность участвовать в миссиях.
  - Пользователь может добавлять игроков в список друзей. 
  - Пользователь может видеть статистику по своим результатам.
  - У пользователя может быть возможность воспользоваться подсказкой, шпаргалкой во время игры.
  - Пользователь может отсортировать задачи (по сложности, тегу).
